### ISSUE TITLE
db schema

### ISSUE THREAD

**Issue by bensoncho** [wzychla/Fido2.NetFramework#1]
After i change the connection string in web.confg to mine database, it works like a charm!
please close the issue :)

**Comment by wzychla** [comment]
The schema is created automatically by the EF before a first query is executed against the database. You just point to an empty, existing database. I've modified the readme to reflect that. Also, added the `Database.SetInitializer` to the global.asax to make it even more explicit.

After you run the demo and any query is executed against the database (e.g. you create the user or try to login), the required tables (three at the moment) are created.

Let me know if the issue can be closed.

**Comment by bensoncho** [comment]
I got it , thank you so much
please close the issue  :)
